#Database
# none This is the default for MySQL, no change to the database structure.
# update Hibernate changes the database according to the given Entity structures.
# create Creates the database every time, but don’t drop it when close.
# create-drop Creates the database then drops it when the SessionFactory closes.

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myshopappdb?useSSL=false
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
